#pragma once

#include <stdint.h>
#include <stdbool.h>

// ----------- Ext instructions -----------

uint8_t emite_dr(uint8_t r);
uint8_t emite_ir(uint8_t r);
uint8_t emite_l(uint8_t d, uint8_t s);
uint8_t emite_ln(uint8_t d, uint8_t s);
uint8_t emite_ld(bool d, bool r, uint8_t s);
uint8_t emite_ldm(bool d, bool r, uint8_t s);
uint8_t emite_ldnm(bool d, bool r, uint8_t s);
uint8_t emite_ldn(bool d, bool r, uint8_t s);
uint8_t emite_ls(uint8_t d, bool s);
uint8_t emite_lsm(uint8_t d, bool s);
uint8_t emite_lsnm(uint8_t d, bool s);
uint8_t emite_lsn(uint8_t d, bool s);
uint8_t emite_mv(uint8_t d, uint8_t s);
uint8_t emite_nr(uint8_t r);
uint8_t emite_s(uint8_t s, uint8_t d);
uint8_t emite_sl(uint8_t d, bool s);
uint8_t emite_slm(uint8_t d, bool s);
uint8_t emite_slnm(uint8_t d, bool s);
uint8_t emite_sln(uint8_t d, bool s);
uint8_t emite_sn(uint8_t s, uint8_t d);

// ----------- Main instructions -----------

uint16_t emit_abs(bool d);
uint16_t emit_add(bool d);
uint16_t emit_addarn(uint16_t s, uint16_t d);
uint16_t emit_addax(bool s, bool d);
uint16_t emit_addaxl(bool s, bool d);
uint32_t emit_addi(bool d, uint16_t i);
uint16_t emit_addis(bool d, uint8_t i);
uint16_t emit_addp(bool d);
uint16_t emit_addpaxz(bool s, bool d);
uint16_t emit_addr(uint16_t s, bool d);
uint16_t emit_andc(bool d);
uint32_t emit_andcf(bool d, uint16_t i);
uint32_t emit_andf(bool d, uint16_t i);
uint32_t emit_andi(bool d, uint16_t i);
uint16_t emit_andr(bool s, bool d);
uint16_t emit_asl(bool r, uint8_t i);
uint16_t emit_asr(bool r, uint8_t i);
uint16_t emit_asrn(void);
uint16_t emit_asrnr(bool d);
uint16_t emit_asrnrx(bool s, bool d);
uint16_t emit_asr16(bool r);
uint32_t emit_bloop(uint8_t r, uint16_t a);
uint32_t emit_bloopi(uint8_t i, uint16_t a);
uint32_t emit_call(uint16_t a);
uint32_t emit_callcc(uint8_t c, uint16_t a);
uint16_t emit_callr(uint8_t r);
uint16_t emit_callrcc(uint8_t r, uint8_t c);
uint16_t emit_clr15(void);
uint16_t emit_clr(bool r);
uint16_t emit_clrp(void);
uint16_t emit_cmp(void);
uint16_t emit_cmpaxh(bool r, bool s);
uint32_t emit_cmpi(bool d, uint16_t i);
uint16_t emit_cmpis(bool d, uint8_t i);
uint16_t emit_dar(uint8_t d);
uint16_t emit_dec(bool d);
uint16_t emit_decm(bool d);
uint16_t emit_halt(void);
uint16_t emit_iar(uint8_t d);
uint16_t emit_ifcc(uint8_t c);
uint16_t emit_ilrr(bool d, uint8_t s);
uint16_t emit_ilrrd(bool d, uint8_t s);
uint16_t emit_ilrri(bool d, uint8_t s);
uint16_t emit_ilrrn(bool d, uint8_t s);
uint16_t emit_inc(bool d);
uint16_t emit_incm(bool d);
uint32_t emit_jmp(uint16_t a);
uint32_t emit_jcc(uint8_t c, uint16_t a);
uint16_t emit_jmpr(uint8_t r);
uint16_t emit_jrcc(uint8_t r, uint8_t c);
uint16_t emit_loop(uint8_t r);
uint16_t emit_loopi(uint8_t i);
uint32_t emit_lr(uint16_t d, uint16_t m);
uint32_t emit_lri(uint16_t d, uint16_t i);
uint16_t emit_lris(uint16_t d, uint8_t i);
uint16_t emit_lrr(uint16_t s, uint16_t d);
uint16_t emit_lrrd(uint16_t s, uint16_t d);
uint16_t emit_lrri(uint16_t s, uint16_t d);
uint16_t emit_lrrn(uint16_t s, uint16_t d);
uint16_t emit_lrs(uint16_t d, uint8_t m);
uint16_t emit_lsl(bool r, uint16_t i);
uint16_t emit_lsl16(bool r);
uint16_t emit_lsr(bool r, uint8_t i);
uint16_t emit_lsrn(void);
uint16_t emit_lsrnr(bool d);
uint16_t emit_lsrnrx(bool s, bool d);
uint16_t emit_lsr16(bool r);
uint16_t emit_m0(void);
uint16_t emit_m2(void);
uint16_t emit_madd(bool s);
uint16_t emit_maddc(bool s, bool t);
uint16_t emit_maddx(bool s, bool t);
uint16_t emit_mov(bool d);
uint16_t emit_movax(bool s, bool d);
uint16_t emit_movnp(bool d);
uint16_t emit_movp(bool d);
uint16_t emit_movpz(bool d);
uint16_t emit_movr(uint16_t s, bool d);
uint16_t emit_mrr(uint16_t d, uint16_t s);
uint16_t emit_msub(bool s);
uint16_t emit_msubc(bool s, bool t);
uint16_t emit_msubx(bool s, bool t);
uint16_t emit_mul(bool s);
uint16_t emit_mulac(bool s, bool r);
uint16_t emit_mulaxh(void);
uint16_t emit_mulc(bool s, bool t);
uint16_t emit_mulcac(bool s, bool t, bool r);
uint16_t emit_mulcmv(bool s, bool t, bool r);
uint16_t emit_mulcmvz(bool s, bool t, bool r);
uint16_t emit_mulmv(bool s, bool r);
uint16_t emit_mulmvz(bool s, bool r);
uint16_t emit_mulx(bool s, bool t);
uint16_t emit_mulxac(bool s, bool t, bool r);
uint16_t emit_mulxmv(bool s, bool t, bool r);
uint16_t emit_mulxmvz(bool s, bool t, bool r);
uint16_t emit_neg(bool d);
uint16_t emit_not(bool d);
uint16_t emit_nop(void);
uint16_t emit_nx(void);
uint16_t emit_orc(bool d);
uint32_t emit_ori(bool d, uint16_t i);
uint16_t emit_orr(bool s, bool d);
uint16_t emit_ret(void);
uint16_t emit_retcc(uint8_t c);
uint16_t emit_rti(void);
uint16_t emit_rticc(uint8_t c);
uint16_t emit_sbclr(uint8_t i);
uint16_t emit_sbset(uint8_t i);
uint16_t emit_set15(void);
uint16_t emit_set16(void);
uint16_t emit_set40(void);
uint32_t emit_si(uint8_t m, uint16_t i);
uint32_t emit_sr(uint16_t s, uint16_t m);
uint16_t emit_srr(uint16_t d, uint16_t s);
uint16_t emit_srrd(uint16_t d, uint16_t s);
uint16_t emit_srri(uint16_t d, uint16_t s);
uint16_t emit_srrn(uint16_t d, uint16_t s);
uint16_t emit_srs(uint16_t s, uint8_t m);
uint16_t emit_srsh(bool s, uint8_t m);
uint16_t emit_sub(bool d);
uint16_t emit_subarn(uint16_t d);
uint16_t emit_subax(bool s, bool d);
uint16_t emit_subp(bool d);
uint16_t emit_subr(uint16_t s, bool d);
uint16_t emit_tst(bool r);
uint16_t emit_tstaxh(bool r);
uint16_t emit_tstprod(void);
uint16_t emit_xorc(bool d);
uint32_t emit_xori(bool d, uint16_t i);
uint16_t emit_xorr(bool s, bool d);
