[package]
name = "tools"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib/lib.rs"

[[bin]]
name = "obj_to_c"
path = "obj_to_c/main.rs"

[[bin]]
name = "dsp-client"
path = "dsp-client/main.rs"

[[bin]]
name = "dsp-gen-tests"
path = "dsp-gen-tests/main.rs"

[[bin]]
name = "dsp-gen-inputs"
path = "dsp-gen-inputs/main.rs"

[[bin]]
name = "iso"
path = "iso/main.rs"

[dependencies]
tobj = "4.0.3"
argp = "0.4.0"
bytemuck = { version = "1.22.0", features = ["min_const_generics", "derive", "extern_crate_std"] }
rand = "0.9.2"
anyhow = "1.0.0"
tempdir = "0.3.7"
